version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./front_end
      dockerfile: Dockerfile
    expose:
      - "80"  # Важно: expose, чтобы nginx мог проксировать трафик
    depends_on:
      - postgres
    env_file:
      - ./front_end/.env
    deploy:
      resources:
        limits:
          memory: 700M

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi-backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    expose:
      - "8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/mydatabase

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front_end/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro  # Монтируем системные сертификаты
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  postgres_data:
